"use client";
import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import { usePathname, useRouter } from "next/navigation";
import "./globals.css";
import Sidebar from "@/components/Sidebar/Sidebar";
import Navbar from "@/components/Navbar/Navbar";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { Toaster } from "react-hot-toast";
import { AuthProvider } from "@/context/AuthContext";
const inter = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

// export const metadata: Metadata = {
//   title: "Workshop Management Portal - IMC",
//   description: "Generated by create next app",
// };

const queryClient = new QueryClient();
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const router = usePathname();
  const authRoutes = ["/auth/login", "/auth/signup", "/forgot-password"];
  const isAuthRoute = authRoutes.includes(router);
  return (
    <html lang="en">
      <QueryClientProvider client={queryClient}>
        <AuthProvider>
          <body
            className={`${inter.className} flex flex-row w-screen h-screen overflow-x-hidden`}
          >
            <div className="flex flex-row w-full">
              {!isAuthRoute && (
                <>
                  <Sidebar /> <Navbar />
                </>
              )}

              <div className="flex-grow ml-20 my-20">
                {children} <Toaster />
              </div>
            </div>
          </body>
        </AuthProvider>
      </QueryClientProvider>
    </html>
  );
}
