"use client";
import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import { usePathname, useRouter } from "next/navigation";
import "./globals.css";
import Sidebar from "@/components/Sidebar/Sidebar";
import Navbar from "@/components/Navbar/Navbar";

const inter = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

// export const metadata: Metadata = {
//   title: "Workshop Management Portal - IMC",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const router = usePathname();
  const authRoutes = ["/auth/login", "/auth/signup", "/forgot-password"];
  const isAuthRoute = authRoutes.includes(router);
  return (
    <html lang="en">
      <body className={`${inter.className} flex flex-row`}>
        <div className="flex flex-row">
          {!isAuthRoute && <Sidebar />}
          <Navbar />
          <div className="flex-grow">{children}</div>
        </div>
      </body>
    </html>
  );
}
